//
//  GesturePerformanceTestViewController.swift
//  Cursor
//
//  Created by Kasper Lind Sørensen on 23/11/15.
//  Copyright © 2015 SimonBS. All rights reserved.
//

import Foundation
import UIKit

class GesturePerformanceTestViewController: UIViewController {
    private let gestureRecognizer = ThreeDollarGestureRecognizer(resampleAmount: 50)
    private let logger = Logger()
    private let loggingDateFormatter = NSDateFormatter()
    private let totalGestureCount = 20
    private let trainingCount = 5
    private let iterationCount = 1000
    private let recognizer = ThreeDollarGestureRecognizer(resampleAmount: 50);
    
    var contentView: GesturePerformanceTestView {
        return view as! GesturePerformanceTestView
    }
    
    init() {
        super.init(nibName: nil, bundle: nil)
        title = localize("ADD_GESTURE")
        navigationItem.leftBarButtonItem = UIBarButtonItem(barButtonSystemItem: .Cancel, target: self, action: "TestGesturePerformance")
    }

    override func loadView() {
        view = GesturePerformanceTestView()
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        contentView.startTestButton.addTarget(self, action: "TestGesturePerformance", forControlEvents: .TouchDown)
        contentView.startTestButton.enabled = true
    }
    
    func TestGesturePerformance(){
        // Empty the DB
        let gestureDB = GestureDB.sharedInstance()
        gestureDB.gestures!.forEach {
            gestureDB.deleteGesturesWithNames($0.gestureID)
        }

        // Start up the logger
        if !logger.isLogging {
            logger.startLogging([
                "gestureNo",
                "time"
                ])
        }
        
        for _ in 1...totalGestureCount{
            // Add new gesture traces to the DB
            for _ in 1...trainingCount {
                GestureDB.sharedInstance().addGesture(CreateRandomGesture())
            }
            let knownGestures = GestureDB.sharedInstance().gestureDict as [NSObject: AnyObject]
            let testGesture = CreateRandomGesture()
            
            // Warmup
            for _ in 1...10{
                recognizer.recognizeGesture(testGesture, fromGestures: knownGestures)
            }
            
            // Test
            let start = NSDate(); // Start time
            for _ in 1...iterationCount{
                recognizer.recognizeGesture(testGesture, fromGestures: knownGestures)
            }
            let end = NSDate();   // End time
            
            let timeInterval: Double = end.timeIntervalSinceDate(start); // <<<<< Difference in seconds (double)
            
            logger.log([
                String(index),
                String(timeInterval)
                ])
        }
        logger.stopLogging()
    }
    
    func CreateRandomGesture() -> Gesture {
        let rowCountUInt32 :UInt32 = 5
        let columnCountUInt32 : UInt32 = 5
        let rowCount = 5
        let columnCount = 5
        let newGesture = Gesture()
        let trace = Matrix(matrixWithRows: rowCountUInt32, andCols: columnCountUInt32)
        
        for row in 0...rowCount-1 {
            for column in 0...columnCount-1 {
                trace.data[row][column] = Float(arc4random())
            }
        }
        
        newGesture.gestureTrace = trace
        newGesture.gestureID = "AutoGenerated Gesture"
        return newGesture
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}